import React from "react";
import Link from "next/link";
import { Metadata } from "next";
import FullLogo from "@/app/(DashboardLayout)/layout/shared/logo/FullLogo";
import LeftSidebarPart from "../LeftSidebarPart";
import SocialButtons from "../../authforms/SocialButtons";
import AuthRegister from "../../authforms/AuthRegister";

export const metadata: Metadata = {
  title: "Side Register Authentication",
  description: "Generated by create next app",
};

const Register = () => {
  return (
    <div className="min-h-screen bg-lightprimary dark:bg-dark">
      {/* Logo Section */}
      <div className="p-5 fixed top-0 left-0 right-0 z-50">
  <FullLogo />
</div>

      {/* Main Layout */}
      <div className="grid grid-cols-12 h-screen pt-20">
        {/* Left Sidebar */}
        <div className="hidden lg:block lg:col-span-7 xl:col-span-8 bg-lightprimary  overflow-hidden">
          <LeftSidebarPart />
        </div>

        {/* Register Form */}
        <div className="col-span-12 lg:col-span-5 xl:col-span-4 flex items-center justify-center px-6 sm:px-12">
          <div className="w-full max-w-md space-y-6">
            <h3 className="text-2xl font-bold text-center">Welcome to NotifyHub</h3>
            {/* <p className="text-center text-sm text-darklink font-medium">
              Your Admin Dashboard
            </p> */}

            {/* Social Buttons */}
            {/* <SocialButtons title="or sign in with" /> */}

            {/* Registration Form */}
            <AuthRegister />

            {/* Already Have Account */}
            <div className="flex justify-center items-center gap-2 text-sm text-gray-600">
              <p>Already have an account?</p>
              <Link
                href="/auth/OtpAuth"
                className="text-blue-600 hover:underline font-medium"
              >
                Sign In
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Register;
